### ISSUE TITLE
Begin Literature Review 

### ISSUE THREAD

**Issue by emilysambuco** [rebeccachapman/AppliedClimate#1]
Rebecca - Name PDFs correct name and add to OneDrive. 
Emily - Start excel document summarizing literature, and place in one drive folder 
Yuechun - find some GIS papers or any articles related to decision support tools that can be of use 
Emily - cover the modeling papers

**Comment by emilysambuco** [comment]
Read through proposals!

**Comment by emilysambuco** [comment]
Yuechun - when looking for relevant literature on spatial applications, I would recommend looking through Zhiying's TDEM proposal. It seems to have quite a few references that could be helpful for us.

**Comment by 94ycwang** [comment]
Ok. Thanks a lot for your reminder.

Yuechun
